import type { Metadata } from "next";
import "./globals.css";
import Header from "@/app/layouts/Header";
import { almarai, cairo } from "./fonts/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="rtl">
      <body
        className={` ${cairo.className} ${almarai.className} bg-[#ddd] antialiased`}
      >
        <Header />
        <main className="mx-auto mt-6 flex max-w-2xl flex-col gap-3">
          {children}
        </main>
      </body>
    </html>
  );
}
