import type { Metadata } from "next";
import "./globals.css";
import Header from "@/app/layouts/Header";
import { almarai, cairo } from "./fonts/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="rtl">
      <body
        className={` ${cairo.className} ${almarai.className} mx-auto max-w-5xl antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
